#%RAML 1.0 Library

types:
  pricebookentry:
    type: object
    properties:
      id:
        type: string
        required: false
      isactive:
        type: boolean
        required: false
      pricebook2id:
        type: string
        required: false
      product2id: 
        type: string
        required: false
      productcode: 
         type: string
         required: false
      unitprice: 
         type: integer
         required: false
      name:
        type: string
        required: false
   
  get_pricebookentry_response:
    type: array
    items: pricebookentry
            
        
    
     

      
